### ISSUE TITLE
AUR deps

### ISSUE THREAD

**Issue by niktob560** [libfuse/pyfuse3#39]
```
==> Запускается build()...
found MANIFEST.in, running in developer mode
running build_cython
Traceback (most recent call last):
  File "/home/nikto_b/.cache/yay/python-pyfuse3/src/pyfuse3-pyfuse-3.2.0/setup.py", line 275, in <module>
    main()
  File "/home/nikto_b/.cache/yay/python-pyfuse3/src/pyfuse3-pyfuse-3.2.0/setup.py", line 117, in main
    setuptools.setup(
  File "/home/nikto_b/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nikto_b/.cache/yay/python-pyfuse3/src/pyfuse3-pyfuse-3.2.0/setup.py", line 218, in run
    version = subprocess.check_output([c, '--version'],
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '--version']' returned non-zero exit status 1.
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
ошибка сборки: python-pyfuse3
```
Error caused because of ``cython`` not installed
```bash
$ cython     
Traceback (most recent call last):
  File "/usr/bin/cython", line 5, in <module>
    from Cython.Compiler.Main import setuptools_main
ModuleNotFoundError: No module named 'Cython'
```
Fixed with
```bash
pip install cython
```
can You fix [AUR package](https://aur.archlinux.org/packages/python-pyfuse3) to provide this dependency?

**Comment by Nikratio** [comment]
I'm afraid the AUR package is maintained independently, I do not know by whom or how to contact them.

**Comment by niktob560** [comment]
Okay, I already contacted maintainer.
