### ISSUE TITLE
TypeError in examples/tmpfs.py

### ISSUE THREAD

**Issue by jheiv** [libfuse/pyfuse3#4]
I'm not sure whether this or libfuse is the more appropriate repo for this, or whether it falls under the exemptions listed [here](https://github.com/libfuse/pyfuse3/blob/master/examples/tmpfs.py#L55:L65), or whether it's even an issue at all and not user error. But debugging it myself has been difficult as trio seems to make it difficult to find the source of the failing task.

Steps to (hopefully re)produce:
- From one console
-- Build HEAD versions of libfuse, pyfuse3
-- `cd pyfuse/examples`
--  `python3.6 tmpfs.py  /home/username/foo`
- From a second, after this is done
-- `cd ~/foo`
-- `touch file`
--`mv file file2`

Console 1: (below)
Console 2:  `mv: cannot move 'file' to 'file2': Software caused connection abort`

```
Traceback (most recent call last):
  File "tmpfs.py", line 495, in <module>
    trio.run(pyfuse3.main)
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 1337, in run
    raise runner.main_task_outcome.error
  File "/home/username/workspaces/vscode/fuse-test/pyfuse3/src/_pyfuse3.py", line 26, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 743, in main
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 397, in __aexit__
    raise combined_error_from_nursery
  File "/home/username/workspaces/vscode/fuse-test/pyfuse3/src/_pyfuse3.py", line 26, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 247, in _session_loop
  File "src/handlers.pxi", line 339, in fuse_rename_async
TypeError: rename() takes 6 positional arguments but 7 were given
```

**Comment by jheiv** [comment]
Could it be that [tmpfs.py:224](https://github.com/libfuse/pyfuse3/blob/master/examples/tmpfs.py#L224) needs to accept a flags parameter?  If I understand the structure of the code, it seems like [handlers.pxi:339](https://github.com/libfuse/pyfuse3/blob/master/src/handlers.pxi#L339) wants to pass it flags.

**Comment by Nikratio** [comment]
Thanks for the report! Yes, the flags argument is most likely the cause. (Apparently there is also a bug in the test cases, they should have caught this)
