### ISSUE TITLE
pyfuse crash if go to the fused directory directly

### ISSUE THREAD

**Issue by jbui007** [libfuse/pyfuse3#7]
Another issue in this new version is that it crashed if you try to go to the directory directly.
This works in the old llfuse module.

```
2018-10-16 16:52:03.801 MainThread: [__main__] lookup for b'vivint' in 385
2018-10-16 16:52:03.803 MainThread: [pyfuse3] Calling fuse_session_unmount
2018-10-16 16:52:03.838 MainThread: [pyfuse3] Calling fuse_session_destroy
Traceback (most recent call last):
  File "jscfs.py", line 410, in <module>
    main()
  File "jscfs.py", line 398, in main
    trio.run(pyfuse3.main)
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 1328, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.6/dist-packages/pyfuse3-0.9-py3.6-linux-x86_64.egg/_pyfuse3.py", line 26, in wrapper
  File "src/pyfuse3.pyx", line 743, in main
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 395, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.6/dist-packages/pyfuse3-0.9-py3.6-linux-x86_64.egg/_pyfuse3.py", line 26, in wrapper
  File "src/internal.pxi", line 247, in _session_loop
  File "src/handlers.pxi", line 65, in pyfuse3.fuse_lookup_async
TypeError: Cannot convert coroutine to pyfuse3.EntryAttributes

```

**Comment by Nikratio** [comment]
Thanks for the report! Could you tell me what file system you are using? Can you reproduce the problem with one of the example? It is also not clear to me what you mean with "going to the fused directory directly" - could you provide the full steps that you are following?

**Comment by jbui007** [comment]
I am using EXT4, Ubuntu 18.04 - I cannot reproduce with the examples, will keep debugging on my end. 
but in the example the directory underneath the main directory is empty so maybe that is why it does not crashed.  

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by jbui007** [comment]
The example works so must be something we doing on our side.  
Closed for now.
